### ISSUE TITLE
New titlebar breaks top bar

### ISSUE THREAD

**Issue by Liz-chan** [BakaTekku/Darker_Discord#1]
Since the new discord update added a title bar, the top bar it shows on servers and DMs are now grey.
Pic for reference.
![image](https://user-images.githubusercontent.com/18467466/32129332-1155565e-bb54-11e7-8dcc-19735d554213.png)

**Comment by BakaTekku** [comment]
@Liz-chan thanks for the heads up should be fixed now.

**Comment by Liz-chan** [comment]
Sweet, it's back to being themed now, thanks!
