### ISSUE TITLE
New friendlist

### ISSUE THREAD

**Issue by lollilol** [BakaTekku/Darker_Discord#12]
ive added
`.da-peopleList,.da-nowPlayingScroller,.da-emptyCard {
    background-color: var(--primary);
}
.da-actionButton {
    background-color: var(--secondary);
}`
to darken the new friend list.

**Comment by lollilol** [comment]
it changed again. new code:
`.da-peopleColumn,.da-nowPlayingScroller,.da-emptyCard {
    background-color: var(--primary);
}
.da-actionButton {
    background-color: var(--secondary);
}`

**Comment by BakaTekku** [comment]
noted, thanks.
