### ISSUE TITLE
gaps between messages

### ISSUE THREAD

**Issue by lollilol** [BakaTekku/Darker_Discord#13]
there are gaps between messages since [commit 5e36c55](https://github.com/BakaTekku/Darker_Discord/commit/5e36c55988fd6f57d54cfb4db21501a34666357f)
[commit c9870a6](https://github.com/BakaTekku/Darker_Discord/commit/c9870a64a07d01427beaded0da695329a6c11d3f) is working fine.

**Comment by BakaTekku** [comment]
[commit c7a5bd8](https://github.com/BakaTekku/Darker_Discord/commit/c7a5bd8778026f980cefbfe09e427a83c5ed9120)

**Comment by lollilol** [comment]
this doesnt fixes it for me.

**Comment by BakaTekku** [comment]
mind sending me a screenshot? @lollilol

**Comment by lollilol** [comment]
this is latest
![image](https://user-images.githubusercontent.com/38194372/74859930-27e08e00-5348-11ea-86c7-935b158e08dd.png)

**Comment by BakaTekku** [comment]
@lollilol thanks I compared commit 5e36c55 & commit c9870a6 and saw i left in a few of my personal tweaks accidentally. let me know if this fixed it for you.

Also Discord Update allows you to go into User Settings > Appearance 
to Adjust "Space Between Message Groups".
