### ISSUE TITLE
Chat box isn't dark like in the screenshots

### ISSUE THREAD

**Issue by Liz-chan** [BakaTekku/Darker_Discord#2]
In the screenshots for the style, the chat box looks darker than the rest of the chat, and I think that looks pretty cool. Right now for me, it's the same color as the rest of the chat, so I'm guessing there's a problem.
![image](https://user-images.githubusercontent.com/18467466/33452428-2da1cb48-d5e0-11e7-8d7c-3737c2d282c5.png)

**Comment by BakaTekku** [comment]
That is actually one of the optional tweaks: "chat_input_background.css"
[Tweaks](https://github.com/BakaTekku/Discord_Theme/blob/master/tweaks)

**Comment by Liz-chan** [comment]
Oh didn't even know you could tweak it, sorry.
