### ISSUE TITLE
Class changed (apparently)

### ISSUE THREAD

**Issue by Liz-chan** [BakaTekku/Darker_Discord#4]
![image](https://user-images.githubusercontent.com/18467466/35030292-7b640a28-fb2c-11e7-8020-a238656e71eb.png)

It looks bad now.

EDIT: Just noticed the emoji picker is messed up too.
![image](https://user-images.githubusercontent.com/18467466/35035874-9afffc02-fb40-11e7-988d-5665b6505a1f.png)

**Comment by Liz-chan** [comment]
If it's any help, this sorta fixes it. It still looks misplaced tho..

`.layers-20RVFW, .layer-kosS71, .container-2OU7Cz, .typing-3eiiL_ {
  background: transparent !important;
}`

**Comment by BakaTekku** [comment]
it's been known for awhile I'm waiting for discord to finish CSS changes.

**Comment by Liz-chan** [comment]
Oh alright, sweet.

**Comment by BakaTekku** [comment]
Ignore this just a reminder for myself 

To do list:
x Emoji Selector
x Context-menus
x is typing
x Private call background
x Quick switch notice
x Server drop-down menu.
x User calling popup
x Status picker
x LFG 
x other tweaks

DONE
